pipeline {
    agent any
    stages {
        stage('Stage1') {
            steps {
                // get current working directory
                echo "Current working directory: ${pwd()}"
                echo 'Stage1 Step1'
            }
        }
        stage('Stage2') {
            steps {
                echo 'Stage2 Step1'
            }
        }
    }
}
