pipeline {
    agent any
    stages {
        stage('Stage1') {
            steps {
                echo 'Stage1 Step1'
            }
            steps {
                echo 'Stage1 Step2'
            }
        }
        stage('Stage2') {
            steps {
                echo 'Stage2 Step1'
            }
            steps {
                echo 'Stage2 Step2'
            }
        }
    }
}
